### ISSUE TITLE
Erreur de compilation PDFLatex avec les titres de chapitres traduits (accents)

### ISSUE THREAD

**Issue by cryptobioz** [Labx/cryptoparty-handbook-fr#6]
Pour créer un fichier PDF depuis les sources, on utilise le script _convert_to_tex.sh_.
Les titres de chapitres écrits dans le PDF proviennent des noms des dossiers, ainsi _chapter_13_secure_file_sharing_ devient _Secure File Sharing_.

Or, lorsque l'on veut utiliser un titre contenant des accents, pdflatex plante : 

```
! LaTeX Error: File `chapter_13_le_partage_de_fichiers_suris00_installing_i
2p_on_ubuntu.md.tex' not found.
```

Si vous avez une solution, je suis preneur.

**Comment by MicroCheapFx** [comment]
En effet, la compilation latex ne supporte que l'ASCII de manière native. 

https://fr.m.wikibooks.org/wiki/LaTeX/%C3%89l%C3%A9ments_de_base#Diacritiques_et_ligatures

Je zieute ça et rajouterai la ligne d'en tête pour le support des caractères accentuées, ou je rajouterai des lignes ses dans le script shell, l'un ou l'autre.

La première solution semble la meilleur car elle pare à toutes exceptions, mais je ne me rappelle pas si ça se fait.

**Comment by cryptobioz** [comment]
Tu parles des sources, non ? J'ai ajouté le support d'UTF-8 dans les sources LaTex (https://github.com/Labx/cryptoparty-handbook-fr/commit/3db95d489add05aa39f3d8723139795b88a788db) et ça semble fonctionner mais le compilateur plante car il ne reconnaît pas l'Unicode dans les noms de fichier.

On pourrait peut-être ajouter un fichier `title` avec le nom du chapitre dans chaque dossier ? Au lieu de lire le nom du dossier, le script lira ce fichier.
